import os, base64, urllib.request, urllib.error, json
from datetime import datetime


def send_report_email(pdf_bytes: bytes, filename: str = "dentvision-report.pdf") -> None:
    api_key = os.getenv("RESEND_API_KEY")
    recipient = os.getenv("REPORT_RECIPIENT", "shubham.2k07@gmail.com")

    if not api_key:
        raise ValueError("RESEND_API_KEY environment variable must be set.")

    pdf_b64 = base64.b64encode(pdf_bytes).decode()

    payload = json.dumps({
        "from": "Dent Vision AI <onboarding@resend.dev>",
        "to": [recipient],
        "subject": f"Dent Vision AI — Damage Report ({datetime.now().strftime('%b %d, %Y %H:%M')})",
        "html": (
            "<html><body style='font-family:Arial,sans-serif;color:#222;'>"
            "<h2 style='color:#0084cc;'>&#9670; Dent Vision AI — Damage Analysis Report</h2>"
            "<p>Your vehicle damage analysis report is attached as a PDF.</p>"
            f"<p style='color:#888;font-size:12px;'>Generated by Dent Vision AI &mdash; "
            f"{datetime.now().strftime('%B %d, %Y at %H:%M')}</p>"
            "</body></html>"
        ),
        "attachments": [{"filename": filename, "content": pdf_b64}],
    }).encode()

    req = urllib.request.Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            if not result.get("id"):
                raise ValueError(f"Resend error: {result}")
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()
        raise ValueError(f"Resend API error {e.code}: {error_body}")
